version: '3'

networks:
  semantix: {}

services:
  web:
    networks:
    - semantix
    build:
      context: '.'
    volumes:
    - .:/srv/app
    environment:
      REDIS_URL: redis://redis:6379/0
      SPARK_URL: spark://spark-master:7077
    ports:
    - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 web:app

  worker:
    networks:
    - semantix
    shm_size: 500mb
    build:
      context: '.'
    volumes:
    - .:/srv/app
    environment:
      REDIS_URL: redis://redis:6379/0
      SPARK_URL: spark://spark-master:7077
    command: celery -A workers worker --loglevel=info

  redis:
    networks:
    - semantix
    image: redis:alpine
