version: '3'

networks:
  semantix: {}

services:
  web:
    networks:
    - semantix
    build:
      context: '.'
    volumes:
    - .:/srv/app
    - /tmp/data:/srv/data
    environment:
      REDIS_URL: redis://redis:6379/0
      SPARK_URL: spark://spark-master:7077
    ports:
    - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 web:app

  worker:
    networks:
    - semantix
    shm_size: 500mb
    build:
      context: '.'
    volumes:
    - .:/srv/app
    - /tmp/data:/srv/data
    environment:
      REDIS_URL: redis://redis:6379/0
      SPARK_URL: spark://spark-master:7077
    command: celery -A workers worker --loglevel=info

  redis:
    networks:
    - semantix
    image: redis:alpine

  spark-master:
    networks:
    - semantix
    image: bitnami/spark:2
    volumes: 
    - /tmp/data:/srv/data
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
      SPARK_RPC_ENCRYPTION_ENABLED: 'no'
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
      SPARK_SSL_ENABLED: 'no'
    ports:
    - 8080:8080

  spark-worker-1:
    networks:
    - semantix
    image: bitnami/spark:2
    volumes: 
    - /tmp/data:/srv/data
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
      SPARK_RPC_ENCRYPTION_ENABLED: 'no'
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
      SPARK_SSL_ENABLED: 'no'

  spark-worker-2:
    networks:
    - semantix
    image: bitnami/spark:2
    volumes: 
    - /tmp/data:/srv/data
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
      SPARK_RPC_ENCRYPTION_ENABLED: 'no'
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
      SPARK_SSL_ENABLED: 'no'
